### ISSUE TITLE
Aviar's Circle not detecting pentacle

### ISSUE THREAD

**Issue by HaydenCour** [klikli-dev/occultism#1000]
**Describe the bug**
After placing the pentagram and all necessary requirements for the ritual and trying to summon a Foliot get an error 
that says "No pentacle found!"

**To Reproduce**
1. Place sacrificial bowls needed
2. Place candles needed
3. Place pentacle needed
4. Right click golden sacrifice with bound Foliot book
5. Receive error saying "No pentacle found!"

**Expected behavior**
Ritual should summon Aldvondline

**Screenshots**
![image](https://github.com/klikli-dev/occultism/assets/101363010/f5006a27-7a73-4d84-94c9-f313018f1881)
![image](https://github.com/klikli-dev/occultism/assets/101363010/0686fcde-ee76-48e2-9446-074e0d3a3f40)

**System (please complete the following information):**
- Occultism Version: 1.89.1
- OS: Windows
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods:  ATM9

**Comment by klikli-dev** [comment]
@HaydenCour please join our discord, we have awesome community helpers who will walk you through diagnosing what is going on, most likely it is an issue with the recipe/ingredients or modpack changes, not with the mod. 

In case it turns out to be a mod issue after all please ping me and I will reopen this issue
