### ISSUE TITLE
Storage system crashes player when opening on a server

### ISSUE THREAD

**Issue by bunbonz** [klikli-dev/occultism#1020]
**Describe the bug**
The storage system is crashing players at random times when they open the storage using the storage actuator keybind.

**To Reproduce**
1. Click Storage Actuator keybind
2. See error

**Expected behavior**
Usually it would open the storage system as usual, but every now and then it crashes me to the point where i have to wipe my player data in order to get back on the server.

**Screenshots**
![image](https://github.com/klikli-dev/occultism/assets/96094245/f66afa6a-a7a9-4d02-9a73-f5108a3e0285)

**System (please complete the following information):**
- Occultism Version: occultism-1.19.2-1.88.0
- OS: Windows
- Minecraft Version: 1.19.2
- Modpack Link and Version, or list of mods: [https://drive.google.com/file/d/1eh-vrvvPc6sYj-PHfIW3zb4jIzPP93pn/view?usp=sharing](url)

**Additional context**
This only happens randomly, I haven't found a reliable way to recreate it other than using the storage system keybind over and over again.

**Comment by klikli-dev** [comment]
@bunbonz This looks like there are items in the storage with an NBT tag bigger than minecraft supports, because the storage system itself does not add any nbt, it only sends the nbt of the items in it.

Can you provide a log for the client and the server? 
Maybe I can find out more. However, if it *is* the too much nbt thing then what we would need to do is identify the mod that provides the item in question. 

When creating an item, modders can specify to only send a limited part of the NBT to the client, if this is properly implemented the crash can be prevented

**Comment by klikli-dev** [comment]
Closing as stale
