### ISSUE TITLE
[1.20.1] Crash when using the dictionary_of_spirits  (modonomiconbook)

### ISSUE THREAD

**Issue by itsdinkd** [klikli-dev/occultism#1033]
**Describe the bug**

**To Reproduce**
1. Open the dictionary of spirits
2. notice the error when hovering on the second item in book
3. Click the first item in book
4. Crash

**Expected behavior**
to work

**System (please complete the following information):**
- Occultism Version:  1.104.1
- OS: [e.g. Windows] w11
- Minecraft Version: 1.20.1

**Additional context**

This is in the latest.log. looks like something is off with the mark down on the latest version of modonomicon
```
[18Jan2024 12:05:35.969] [Render thread/WARN] [Modonomicon/]: BookErrorManager.error() called for book: occultism:dictionary_of_spirits with error: BookErrorInfo{ 
errorMessage='Cannot render markdown for book 'occultism:dictionary_of_spirits because of errors during book build'', 
context='', 
exception=''
}
```

crash report https://mclo.gs/pmkkNb4

**Comment by klikli-dev** [comment]
@itsdinkd can you attach the latest.log as well? The book should not get into that situation (if a markdown error happens it should show the error written in the book, instead of crashing), it looks almost as if there was an error so bad it caused the error management to fail 

Edit: just tested, when just used with occultism + dependencies the book works. 
Can you try if the crash reproduces for you if you use minimal setup in curseforge or your launcher with just occultism + required / optional dependencies?

**Comment by klikli-dev** [comment]
https://github.com/klikli-dev/modonomicon/commit/9082147d2f5dbd28565d2b31a59533e157b9aed7 (latest modonomicon) introduces a more graceful error handling that should prevent the crash, but will not fix the underlying issue. 
I will close this issue, but please ping me if you have the latest-log available and this still happens
