### ISSUE TITLE
Update recipe tags for crafting with modern tag names

### ISSUE THREAD

**Issue by ffuentesm** [klikli-dev/occultism#1064]
I noticed that the mod still uses "forge:raw_ores" tag, as well as some older tags for the recipe. 
Could you update it to the "forge:raw_materials" tag? As it's the newer updated tag for crafting. This would make things compatible in JEI
https://github.com/klikli-dev/occultism/blob/version/1.20.1/src/main/resources/data/occultism/recipes/crafting/raw_silver_block.json
https://github.com/AlexModGuy/Ice_and_Fire/blob/1.20/src/generated/resources/data/iceandfire/recipes/raw_silver_to_raw_silver_block.json
https://github.com/BluSunrize/ImmersiveEngineering/blob/1.20.1/src/generated/resources/data/immersiveengineering/recipes/crafting/raw_silver_to_raw_block_silver.json
![image](https://github.com/klikli-dev/occultism/assets/44974827/02d4926c-1c15-4ee4-8c2f-82a42cccb0d6)

**Comment by klikli-dev** [comment]
This seems rather odd, because I remembered that someone updated the tags - and indeed silver is tagged as raw_materials/silver

It just also retained the older forge raw_ores tag (it has both) 

What I can do is remove the raw_ores tags as that is probably safe now, but not sure if that will solve the issue

**Comment by ffuentesm** [comment]
Thanks, it fixed. 
You did update the Tags on the items. But the recipes were still using the old tags in their files. 
Now it's working, thanks.
