### ISSUE TITLE
Feature request: Golden bowl redstone signal for automation

### ISSUE THREAD

**Issue by Ciege666** [klikli-dev/occultism#1095]
Feature request:
KJM 
Would it be possible to make the golden bowl lock and emit a redstone signal while crafting? It would make it easier to automate. Right now it disables the ritual if you spam the bowl with the book.

Signal strength's for automation:
0 = Empty
1 (Pulse) = Incomplete Ritual 
2 = Crafting
4 = Sacrifice required
8 (pulse) = completed

**Comment by Kevin-Marsh** [comment]
I would suggest that pulsing redstone modes be avoided. AE and RS both have features where redstone can lock the crafting and wait to insert a new craft until the redstone is removed. Avoiding pulsing redstone and ensuring a seamless transition between the redstone states would ensure that the crafting remains locked. Having varying redstone shouldn't matter and you can easily use them for diagnostics which would be helpful.

Another recommendation I would like to make, though I do not know if it is possible, would be to allow the items to also be piped into the sacrificial bowl rather than only right clicked. It would allow for far more flexible logistics for automation as well.
