### ISSUE TITLE
[1.20.1] Сrashes when opening recipes in EMI with JEI

### ISSUE THREAD

**Issue by Margatroidu** [klikli-dev/occultism#1104]
The latest Occultism version (1.123.0) where you added native EMI support when opening recipes in EMI crashes the game when i opening recipes.
I think it's because EMI recipes conflict with JEI recipes, which I have installed to support recipes from other mods

Crash report:
[crash-2024-03-31_10.39.34-client.txt](https://github.com/klikli-dev/occultism/files/14814719/crash-2024-03-31_10.39.34-client.txt)

**Comment by klikli-dev** [comment]
I think you have the wrong version of smartbrain lib installed (forge version on neoforge or vice versa), which causes the crash. See also https://github.com/Tslat/SmartBrainLib/issues/57#issuecomment-1891803412

It is only triggered by by jei/emi because emi tries to draw one of the entities that uses a smartbrain.

**Comment by Margatroidu** [comment]
Yes, indeed. Thanks for the quick response!
