### ISSUE TITLE
Iesnium Ore not Highlighting

### ISSUE THREAD

**Issue by Seawardrelic** [klikli-dev/occultism#1110]
**Describe the bug**
When my friend and I go to the nether and try to use the diving rod to find Iesnium ore it never highlights so it's very hard to find. I saw previous reports saying to change the useAlternativeDivinationRodRenderer setting to true but after doing that we still have the same issue.

To Reproduce
1. Go to the nether
2. use divining rod
3. No ore gets highlighted even if very close

Expected behavior
I had expected the rod to highlight the ore showing me exactly where it is when I get close enough.

Screenshots
N/A

System (please complete the following information):
- Occultism Version: Occultism 1.20.1-1.124.3
- OS: [e.g. Windows] Windows
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: https://www.curseforge.com/minecraft/modpacks/chosens-modded-adventure

**Comment by klikli-dev** [comment]
Let us diagnose what is going on.
Can you please spawn iesnium ore or otherworld wood in its hidden form (in jei they will show up as "netherrack" and "oak wood" respectively, but with "occultism" instead of "minecraft" as mod id) and place it on the ground. Make sure it shows up as netherrack or oak wood when placed.

Then attune the rod to it and use it. Does it highlight? Does a particle effect fly towards it (in case theurgy is installed)?

**Comment by Seawardrelic** [comment]
https://youtu.be/_UZXZIzka8k
that video shows me checking both the netherrack and wood but getting no highlighting

**Comment by klikli-dev** [comment]
Thank you! Ok that is very clear. It finds the block (the crystal is purple) but doesn't highlight it.
I will test on my end, but it really looks like a useAlternativeDivinationRodRenderer issue - maybe a new "variant" of that.
What graphics card do you use (the vendor is enough: NVidia, AMD, Intel, ... )

**Comment by klikli-dev** [comment]
I just downloaded the latest version of the pack, went into a world and spawned one oak log and one "occultism oak log" aka otherworld wood in disguise.

The outlining works:
![image](https://github.com/klikli-dev/occultism/assets/60774993/1b65f363-8a7d-47d2-8ac6-faa43f1e67dd)

However, with the default shaders enabled it is less visible, they seem to intefere.
My recommendation would be that you try to disable the shaders, and if you are on an AMD card make sure that useAlternativeDivinationRodRenderer is properly configured (do not add it anywhere, just switch the false to true in the occultism-client.toml file)

**Comment by Seawardrelic** [comment]
My friend and I both have AMD cards and our server has the useAlternativeDivinationRodRenderer setting set to true.
![Screenshot 2024-04-12 113401](https://github.com/klikli-dev/occultism/assets/166668238/9d0640d8-9d86-47fa-bf54-35fc0c16dd98)
Also even after turning off the shaders we still do not see that outline.

**Comment by klikli-dev** [comment]
Yeah that looks correct, thanks for confirming!
This is a bit tricky. It is possible that the AMD side broke again but I am not sure how to fix it because I don't have an AMD card to test on.

Mid term my recommendation would be to install theurgy - you do not need to use it, but it modifies the effect of the rod to show a particle instead that should work on all GPUs

**Comment by Seawardrelic** [comment]
Adding Theurgy added the particle effect. Thank you!
