### ISSUE TITLE
Help, ritual requesting bedrock instead of candles

### ISSUE THREAD

**Issue by HugoPereira1999** [klikli-dev/occultism#1137]
Hey, so I've started playing a modpack called "Skyward Colonies" and wanted to go in to the Occultism mod, but unfortunately the rituals keep asking for bedrock instead of candles, even when candles are used it still doesn't recognize them.

![2024-06-28_15 13 37](https://github.com/klikli-dev/occultism/assets/43534641/25a1d453-3f4b-48ef-a38d-e22e063a64d6)
![2024-06-28_15 00 51](https://github.com/klikli-dev/occultism/assets/43534641/1fd03faa-b137-4261-babc-4d6bd0cf52a4)
![2024-06-28_15 01 11](https://github.com/klikli-dev/occultism/assets/43534641/08e3d954-dbb0-4d09-b688-cebbf772010c)

- Occultism Version: 1.122.0
- OS: Windows 10 pro
- Minecraft Version: 1.20.1
- Modpack: https://www.curseforge.com/minecraft/modpacks/skyward-colonies

Ive seen this issue before here https://github.com/klikli-dev/occultism/issues/1062#issuecomment-1960644857) that was happening with the supplementaries but this modpack doesnt use this mod, ive also already done a binary search but it always breaks the modpack.

**Comment by klikli-dev** [comment]
@HugoPereira1999 this is usually caused by other mods modifying the candle tag (making it empty).

This could also be due to crafttweaker/kubejs scripts modifying tags.
You mention you did a binary search, what results did you get?
Or the other way around: If you just put occultism + dependencies + jei in a curseforge profile, does it work?

**Comment by klikli-dev** [comment]
Closed as stale
