### ISSUE TITLE
How to Tell Which Pentacle Is Which (*edited for clarity)

### ISSUE THREAD

**Issue by ratkinsonuk** [klikli-dev/occultism#1138]
I've played the mod a few times, and one of the things that makes it difficult is not knowing which ritual (drawing on the ground) is which, especially when you have 6 or 7 of them scattered about.

Can I suggest a couple of options.

1) A new block that can be written on, or automatically gets the ritual name as part of the creation. At the moment I'm using valilla signs, but something that fits in with the mod would be great.

2) When you look at the centre golden bowl, it shows the name of the ritual above it.

Thanks, Rob.

**Comment by ffuentesm** [comment]
I do like the second suggestion of the Golden Bowl showing the ritual name. Another option would be similar to [Traveler's Titles](https://modrinth.com/mod/travelers-titles/gallery) that makes the name show up on the screen when you enter the circle. 

Also, something that bothered me about the circle. 
I am not sure if this is a feature that was added or removed. But I feel the Circles should be "Upgradable" Like, since there are 4 tiers of crusher demons, I feel that the Circle for the Foliot should be the base, and you made additions to the circle to get the Djinn, and so on. The idea would be that you could still perform the lower-tier rituals while using a high-tier circle since the original circle is still part of the bigger circle. 

Because I also get lost in how many circles I have to make, as well as there are circles that I make just once and never again. 
So I feel that There should be just a few types of circles, and then tiers for those types. 
So A Circle for Summing, a CIrcle for Binding, and a Circle for Possession. Then you would get Tiers for each type, that way you could use the same circle with different sacrificial items for the crafts. 

I think this is already in the mod, as we have a Foliot tier, a Djinn tier, Afrit tier, and Marid tier. 
But looking at the 3 types of circles tier progressions, they all look different, so it feels less like "expanding your ritual circle" and more like "you need 12 different circles" to do the crafts.

**Comment by klikli-dev** [comment]
> I've played the mod a few times, and one of the things that makes it difficult is not knowing which ritual (drawing on the ground) is which, especially when you have 6 or 7 of them scattered about.
> 
> Can I suggest a couple of options.
> 
> 1. A new block that can be written on, or automatically gets the ritual name as part of the creation. At the moment I'm using valilla signs, but something that fits in with the mod would be great.
> 2. When you look at the centre golden bowl, it shows the name of the ritual above it.
> 
> Thanks, Rob.

Fair point, this is something I should look into. I have to look into how to do this in a performant manner, as currently the evaluation of a pentacle is lazy (that is, when a ritual starts, it checks for the pentacle, there is no ongoing awareness of which set of blocks is a pentacle). But that should be solvable :)

**Comment by klikli-dev** [comment]
> Also, something that bothered me about the circle. I am not sure if this is a feature that was added or removed. But I feel the Circles should be "Upgradable" Like, since there are 4 tiers of crusher demons, I feel that the Circle for the Foliot should be the base, and you made additions to the circle to get the Djinn, and so on. The idea would be that you could still perform the lower-tier rituals while using a high-tier circle since the original circle is still part of the bigger circle.
> 
> Because I also get lost in how many circles I have to make, as well as there are circles that I make just once and never again. So I feel that There should be just a few types of circles, and then tiers for those types. So A Circle for Summing, a CIrcle for Binding, and a Circle for Possession. Then you would get Tiers for each type, that way you could use the same circle with different sacrificial items for the crafts.
> 
> I think this is already in the mod, as we have a Foliot tier, a Djinn tier, Afrit tier, and Marid tier. But looking at the 3 types of circles tier progressions, they all look different, so it feels less like "expanding your ritual circle" and more like "you need 12 different circles" to do the crafts.

@ffuentesm Not sure if you are currently in Discord, but someone in the ATM team created a datapack for exactly that, there is one circle that is ever-growing and backwards compatible with early tier rituals. I decided against using it as the default (as a whole meta has developed around the different circles and how to set them up economically and stylistically), but the datapack was linked in discord. It is also compatible with the dictionary of spirits, so the correct circle is displayed for each ritual.

**Comment by ffuentesm** [comment]
No, I am not on Discord, but I would appreciate a lot that Datapack if possible. 
I just think that needing 11 different circles bloats things up and makes me lost when crafting. 
I would prefer the idea of "growing your circles" as you progress. Not to have just 1 circle, but 3 main circles for the main 3 functions. 

It's funny because when I look at the Marid circles, they are identical. The difference is that the Binding one adds 4 soul crystals to the circle. 

<img src= https://github.com/klikli-dev/occultism/assets/44974827/221ea760-539e-4dc4-b74e-7ad737fda2ba alt= placeholder width= 400 height= 400> <img src= https://github.com/klikli-dev/occultism/assets/44974827/80f20785-2ab4-4d05-998b-7f092a0b8157 alt= placeholder width= 400 height= 400>

While the Abras' Conjure and Abras' Commanding Conjure are identical, just changing that outer white marks with yellow ones
<img src= https://github.com/klikli-dev/occultism/assets/44974827/577373df-c4f9-47a2-b8ec-22cc8eb1f15d alt= placeholder width= 400 height= 400> <img src=https://github.com/klikli-dev/occultism/assets/44974827/11702359-3df7-4dfd-b4ba-2aa926b885e5 alt= placeholder width= 400 height= 400>

**Comment by klikli-dev** [comment]
![image](https://github.com/klikli-dev/occultism/assets/60774993/16867c76-540d-4861-a109-599354ce9243)
![image](https://github.com/klikli-dev/occultism/assets/60774993/7d6802c5-091b-4b88-af15-99a8d047f93a)
