### ISSUE TITLE
Server crashing when making the Foliot Crusher

### ISSUE THREAD

**Issue by Paxination** [klikli-dev/occultism#1139]
When i craft the foliot crusher, the most basic crusher, the server crashes when the ritual completes.

1. start ritual
2. when it completes, server dies

this is in the dw20 1.20.1 mod pack, 1.14.0
occultism is 1.132.1
modonomicon is 1.73.0

[crash-2024-06-30_23.43.28-server.txt](https://github.com/user-attachments/files/16047816/crash-2024-06-30_23.43.28-server.txt)

believe this is on neoforge.  I think. not sure what that mod pack uses

**Comment by klikli-dev** [comment]
@Paxination this happens if the wrong version of smartbrainlib for your mod loader is installed.
Your pack is on neoforge, but the smart brain lib version is for forge.

Make sure to place the neoforge version and it will work. This might be an issue in the pack (contact the makers to fix it then) but it could also be a local issue due to curseforge launcher messing up.

**Comment by Paxination** [comment]
Just an FYI I am posting this to ftb github.  and for anyone else, both server and clients need to change to the correct version of smartbrainlib.  fixes the issue as stated.
