### ISSUE TITLE
Linking to storage only yields an item count of one each

### ISSUE THREAD

**Issue by Seegras** [klikli-dev/occultism#1146]
**Describe the bug**
Before the change to the types based storage, you could use the occultism storage as external storage for something else, from tinkers to AE2 and RS. It would show the correct amount of items in the inventory.
Since the change, all items only appear to be in an amount of "1". Crafting still works, but it breaks autocrafting completely. 

**Screenshots**
![2024-07-07_07 02 41](https://github.com/klikli-dev/occultism/assets/1655796/d3d66ba3-b444-416b-8c5f-eb638c12d640)
(on the left you can see the wormhole with the AE2 external storage adapter.)

**System (please complete the following information):**
- Occultism Version: occultism-1.21-neoforge-1.134.6.jar
- OS: Linux
- Minecraft Version: 1.21
- Modpack Link and Version, or list of mods: ATM10 1.0.8 (https://www.curseforge.com/minecraft/modpacks/all-the-mods-10)

**Comment by klikli-dev** [comment]
I'll have to investigate, because there was no change that should directly cause that.
@Seegras When you tested this before the storage rework, did it accurately report the numbers that were also shown in the storage actuator? Or just an approximate number or just anything > 1? 

EDIT: All good, I found the issue. I overlooked something when changing the storage data structure.
