### ISSUE TITLE
Add EMI Transfer Handler support for Storage Actuator

### ISSUE THREAD

**Issue by Seegras** [klikli-dev/occultism#1147]
This could also be a problem of EMI.

It's not possible to click "+" in EMI https://www.curseforge.com/minecraft/mc-mods/emi to fill out a recipe when crafting on occultism storage terminals (except if the ingredients are in the players inventory)

**System (please complete the following information):**
- Occultism Version: occultism-1.21-neoforge-1.134.6.jar
- OS: Linux
- Minecraft Version: 1.21
- Modpack Link and Version, or list of mods: ATM10 1.0.8 (https://www.curseforge.com/minecraft/modpacks/all-the-mods-10)

**Comment by klikli-dev** [comment]
@Seegras does this work with just JEI, if emi is removed? 
Trying to figure out how this relates to https://github.com/klikli-dev/occultism-feature-tracker/issues/5

EDIT: Ok it seems to be working in JEI but not in EMI, but not because it is broken, rather because the EMI recipe transfer handler was not implemented when EMI support was added.

I took a quick look and it is not trivial to convert the JEI one, as they seem to use different concepts. I'll convert this to a feature request, it will likely take some time to implement, especially because I am not familiar with EMI (the integration was done by a community member)
