### ISSUE TITLE
[1.21][NeoForge] Bound books not generating names

### ISSUE THREAD

**Issue by ffuentesm** [klikli-dev/occultism#1171]
**Describe the bug**
Bound books have no names when crafted

**To Reproduce**
1. craft a spirit book
2. bind it

**Expected behavior**

**Screenshots** 
![image](https://github.com/user-attachments/assets/6c1c0966-7192-428a-8a63-bf3c9d3bd2e0)
![image](https://github.com/user-attachments/assets/cc26c8b4-ea47-4743-9d1e-ee5960da3a87)

**System (please complete the following information):**
- Occultism Version: occultism-1.21-neoforge-1.139.2

**Additional context**
I have Inventory profile Next for fast crafting, but I don't think that is affecting it.

**Comment by klikli-dev** [comment]
@ffuentesm can you try this in an occultism-only (+ jei/emi if needed) environment (no fast crafting)? 
I just tested this with a simple curseforge 1.21 profile with just occultism, and the moment I actually take the result book from the crafting grid, I get a name.

This is expected behaviour in 1.21 due to the changes to nbt/components and when I can safely initialize them. 
Maybe fast craft skips the "onCrafted" call which I use to set the data? 
If that is the case we would have to ask them what better way there is to do that and still be compatible with them

**Comment by ffuentesm** [comment]
I just re started the game. 
I tried crafting it manually without changing anything. It generated a name. 
I also tried the fast crafting, and it worked. 

No idea what happened.
