### ISSUE TITLE
Server Crashes when both JEI 19.8.2.99, Modonomicon and Occultism are installed

### ISSUE THREAD

**Issue by AndreCelso** [klikli-dev/occultism#1192]
**Describe the bug**
My Neo Forge Server on 1.21 crashes with the latest JEI at this time when modonomicon-1.21.1-neoforge-1.99.1 and occultism-1.21.1-neoforge-1.151.1 are present

1. Install both mods in the specified version 
2. Run the Server
3. Server Crashes during the mods loading phase

**System**
- Occultism Version: occultism-1.21.1-neoforge-1.151.1
- OS: Windows 11
- Minecraft Version: Minecraft 1.21
- Kitchen Sink Modpack

Latest Log and a screenshot of what happens on client:
Server latest:
[latest.log](https://github.com/user-attachments/files/16641627/latest.log)

![image](https://github.com/user-attachments/assets/5c8bc1c5-ca53-4ecd-8c7d-e8bd4f01913a)

**Comment by klikli-dev** [comment]
As the screenshot and log say, updating JEI (ideally to latest) will fix this.

Is there a reason a JEI update is not possible? In that case I can look into downgrading the JEI requirement on my end. The higher version requirement is intentional as I moved past some JEI deprectations that happened in 19.8.5.0
