### ISSUE TITLE
Fix worldgen config being ignored - moves worldgen config back to common config - config location /config

### ISSUE THREAD

**Issue by Tyrius1** [klikli-dev/occultism#130]
**Describe the bug**
I disabled the copper ore gen in both the server and common files and it still generates in the world. 

Config:
https://pastebin.com/2Lin9Hjm

**System (please complete the following information):**
- Occultism Version: 1.0.6
- Windows
- Minecraft Version: 1.16.4
- Fresh Profile with just occultism

**Comment by klikli-dev** [comment]
@Tyrius1 thank you for the report!
I am pretty sure that the ore gen config works conceptually (as that has been tested beofre), but there may be an issue with reading the config file, as that was changed from common to server last patch. 

Let's try to narrow down where the issue may be, or how I can reproduce it
Is there a config file in /`saves/<world-name>/serverconfig/occultism-server.toml` on your end?

**Comment by Tyrius1** [comment]
there is. i copied it into default config and changed the default config

**Comment by bessiq** [comment]
I'm having the same issue. I disabled copper and silver ores in the new server config, and dropped the file into defaultconfigs. In a new world's serverconfig folder, I can confirm those ore gen settings are still false. But copper and silver ores are still generating. So as you said, it seems like it's just not reading the config.

Let me know if you need any more info!

**Comment by klikli-dev** [comment]
Thank you for the input! I'll try and reproduce it on my end, without a debugger this would be tricky to diagnose :)

**Comment by klikli-dev** [comment]
@Tyrius1 @bessiq turns out this is how forge's server config works. It is not loaded at worldgen time, thus uses the default values.
For the next patch the worldgen settings will therefore move back to common config. Sorry for the back and forth, I was not aware this should not be done in server config. 

@Ridanisaurus @NillerMedDild not sure if you are currently relying on the config for worldgen, but in case you do, here's a ping.

Hopefully going forward config locations will be stable!
