### ISSUE TITLE
feat: Add curio to store familiars and passively apply effect while worn

### ISSUE THREAD

**Issue by klikli-dev** [klikli-dev/occultism#169]
Awesome idea, huh?
Now we just need time to implement this :)

**Comment by Hequinoxe** [comment]
I agree it's an assome idea. A small issue I am meeting currently is that my way of traveling long distance is by leaping with ars nouveau spell(IMO occultism and ars nouveau goes very well together since the mechanics are completely different and the results are complementary). The drikwing cannot keep up and i lose him along the way... so to protect it, as soon as I travel I leave it at home. keeping it in curios would resolve the matter. Unless there's a way to put it on your shoulder? I tried but was unable to do so.
