### ISSUE TITLE
In world pentacle visualization not selecting correct depiction when selected from dictionary of spirits

### ISSUE THREAD

**Issue by GingerSnap-xx** [klikli-dev/occultism#175]
Exiting and re-joining the server did not resolve
Completely restarting minecraft did not resolve

Examples:
Trying to visualize Strigeor's Higher Binding results in the attached image.
![occultism_bug](https://user-images.githubusercontent.com/1896889/106850203-ad546f80-6679-11eb-9515-0e7501a2c388.png)

Running Enigmatica 6 0.3.13 / Forge 1.16.5

**Comment by klikli-dev** [comment]
Can you please provide further information regarding the posted image? It looks like you are placing it on a ceiling.

That said, visualization is handled entirely by the mod patchouli - so it is likely that the issue cannot be resolved on my end.

**Comment by GingerSnap-xx** [comment]
> Can you please provide further information regarding the posted image? It looks like you are placing it on a ceiling.
> 
> That said, visualization is handled entirely by the mod patchouli - so it is likely that the issue cannot be resolved on my end.

I am putting it on the ceiling, but that's just because my floor at the time was a bit holy. Understood regarding visualizations. 

Would you like for me to create the bug report over there, or do you have a process for moving those over?

Regardless closing here as it sounds like it will make it over there in some way before it is worked.

Also, Thanks for your hard work on the mod. I am enjoying it very much.

**Comment by GingerSnap-xx** [comment]
> Can you please provide further information regarding the posted image? It looks like you are placing it on a ceiling.
> 
> That said, visualization is handled entirely by the mod patchouli - so it is likely that the issue cannot be resolved on my end.

I reviewed it more and while It may not change anything, more context is always better.

It looks like it is generating **almost** the correct design.

E.g. Abra's Conjure draws everything but the wither and regular skulls
Strigeor's Higher Binding is missing the four bowls on the outside of the pentacle.
Ophyx' Callin gis missing the bowls and skulls.

It seems largely limited to bowls and skulls.
It does this regardless of whether it's on the ceiling or floor.

**Comment by klikli-dev** [comment]
Thank you for elaborating!
This is not a bug / not a bug I can address:
- The bowls are only in the preview, as they are not a required part, only a suggestions where they can be placed. You can place as many bowls as you like on any block within 8 blocks of the center. I acknowledge that something needs to change there to clarify this, I will likely remove them even from the book.
- Skulls are not rendered as blocks in Minecraft, but Patchouli uses the block render pipleline for the in-world preview, that's why they don't show. You can open an issue in the patchouli github about rendering skulls, however it is my understanding that it is a non-trivial change.
