### ISSUE TITLE
Changing the summoning system to work like how the book seemed to say it worked

### ISSUE THREAD

**Issue by Evalgan** [klikli-dev/occultism#176]
**Is your feature request related to a problem? Please describe.**
Not really as much of a problem, per se, but something that I expected the mechanics of the spirit summoning to be when I first read through the book. I expected that all Foliots and Djinns that were in the world would be subject to decay, and that the Books of Calling could be bound to a spirit in the world to give you control options over them as well as allowing them to return to the Otherworld to let their decay recover. I also expected that the circle used would determine the tier of spirit, while the items used would determine the role. This way, you would be able to summon spirits of any tier to serve you with a variety of functions. Perhaps the ones that are higher tier than Djinns are hostile when they first spawn in, resistant to the summoner's command, and require you to best them in a boss fight before they will serve you. But as a tradeoff, they give you items that you can only get from beating them when you win, they can do a lot more, and they are not subject to decay while working much faster. I don't know if any of this was what you plan for the mod already, but this was how I expected all of these mechanics to work when I read the parts of the book describing Spirits and Decay and saw that each tier of spirit had a different summoning circle.

**Comment by klikli-dev** [comment]
While not all of that is what I had in mind, some of it hits the mark pretty well.
In the end I opted for the less consistent but somewhat simpler to implement mechanics, due to time constraints.
One day I might re-work the entire system to go more in that direction, but for now I will close this issue as it's not feasible.

That said, thank you very much for elaborating your view, I will give you a ping here if and when I make changes to the system!
