### ISSUE TITLE
WARNING: Breaking change for Datapack Recipes for Rituals! - Add jei integration for ritual ingredients

### ISSUE THREAD

**Issue by klikli-dev** [klikli-dev/occultism#219]
- [x] extend ritual_ingredients recipes to contain the activation and result items so it can be searched on jei
  - that means, basically merge "rituals" recipes and "ritual_ingredients" recipes
  - minecraft:air if there is no item output
- [x] add another input to ritual_ingredients that is the id/translation key for the required pentacle
- [x] add a second output to ritual_ingredients recipes, that allows to add a dummy item that represents the ritual
- [x] create ritual dummy items
  - [x] name is the name of the ritual
  - [x] tooltip is a brief description of what the ritual does

**Comment by klikli-dev** [comment]
See #218 
But frankly, it's just something that should exist regardless of Patchouli issues

**Comment by MuteTiefling** [comment]
I think having some fake items would be a very simple and easy way to implement this, yeah. Maybe add a tooltip to them so that when the player mouses over them in the recipe, it can add whatever extra info you want.

Alternatively, while it's not part of a recipe, it might be helpful in figuring out the code: Just Enough Professions displays active renders of Villagers in their JEI integration. 

![image](https://user-images.githubusercontent.com/9543430/117452287-925ff880-af11-11eb-88e0-073b09518ae9.png)


PneumaticCraft does something similar too. It's rendering blocks, however, and I'm not sure if rendering a block vs an entity lines up to be the same thing in the code, but it could be worth a peek.

![image](https://user-images.githubusercontent.com/9543430/117452415-bc191f80-af11-11eb-9190-06dd6a9fffca.png)

Interactio might also be a good one to look at for displaying the actual input items. It's got a nice system where they're all displayed in a circle. In your case, this could be a circle of items around the main ritual trigger (books, I think in most cases, right?) 

![image](https://user-images.githubusercontent.com/9543430/117452828-39dd2b00-af12-11eb-8e86-c735d296feff.png)

**Comment by MuteTiefling** [comment]
Oh, Resourceful Bees might be another good source of inspiration for this since they show their bees in a lot of recipes in JEI. 

![image](https://user-images.githubusercontent.com/9543430/117478602-5fc3f900-af2d-11eb-98c6-8770a9b3db57.png)
