### ISSUE TITLE
Delayed Pickup for crusher spirits - configured via `crusherResultPickupDelay`

### ISSUE THREAD

**Issue by MuteTiefling** [klikli-dev/occultism#270]
**Is your feature request related to a problem? Please describe.**
Crusher spirits have a bit of a habit of getting overly excited in their crushing. They will, for instance, pick up a diamond ore, crush it, then instantly pick up the diamond and crush it to dust. 

Even when tossing them a large quantity, they'll inevitably pick up the last few items they crushed and re-crush them if possible. Makes it a bit difficult to work with things that have multiple crushing steps like gems or even cobble/gravel/sand.

**Describe the solution you'd like**
Implement a 3 second cooldown on all items dropped by the crusher spirits. During this 3 second period, no other crusher spirits can pick up these items. That should give plenty of time for a janitor or other collection system to pick up the items. 

**Additional context**
Holy cow these guys are good at their job :D

**Comment by MuteTiefling** [comment]
Alternate solution: Give these guys a filter similar to the transporters.

**Comment by klikli-dev** [comment]
Ah yes this totally should have been a thing from the start. I'll look into the cooldown first, because should be pretty simple - if not i'll go for the filter, as that has some merit in general (although, I think there is a certain charm in having to set up a chain of spirits and machinery instead of one thing that does it all [server admins generally do not appreciate that charm though :D ])
