### ISSUE TITLE
Suggestion: Add a method for adding loot to the Dimensional Mineshaft

### ISSUE THREAD

**Issue by ArchmageMomo** [klikli-dev/occultism#28]
**Is your feature request related to a problem? Please describe.**
There is no easy way for users to add loot (stones, ores, etc.) to the loot table of the Dimensional Mineshaft.

**Describe the solution you'd like**
A config file in which a user can add or remove Dimensional Mineshaft loot (and probably configure drop chances).

**Comment by klikli-dev** [comment]
The miner actually uses a custom recipe type to allow this. In order to modify or extend the mineshaft loot you can use vanilla Minecraft data packs. 
In https://github.com/klikli-dev/occultism/tree/master/src/main/resources/data/occultism/recipes/miner each mineable resource has a recipe, where the ingredient is the type of miner that can mine this resource (this ingredient can be a tag as defined in https://github.com/klikli-dev/occultism/tree/master/src/main/resources/data/occultism/tags/items/miners ), the result is the mined item and the weight is the chance of mining the item.
