### ISSUE TITLE
Crafting speed augments for rituals of some kind please?

### ISSUE THREAD

**Issue by Dragnier** [klikli-dev/occultism#508]
Ritual crafting is far too slow by default.

Perhaps having more of specific items placed around the pentacles could increase their speed? Various tiered items like candles, skulls, effigies, etc. would fit the theme. Some items could just be findable/craftable without tons of resources but would only give limited benefits while more resource intensive ones would give higher speed benefits as a reward for the effort to get them.

**Comment by SteamDoge9000** [comment]
ive noticed this too, but I think tick acceleators speed it up so that can do for now

the folloing items are considred such

Time in a bottle: Extra Untilities; can apply levels of time to speed up the thing, but cost acumulated time when the item is in your invintotry and unpaused (real game time)

Fast Fowrard (currently using): Schools of magic, second semester; a spell that will cause things to have extra ticks

Hologronium Ritual: Astral Sorcery; a ritual that will cause anything within its range to have extra ticks (faster time)

**Comment by klikli-dev** [comment]
After thinking about it for a while, I think between the configurability of the duration via recipe and external tick accelerators this should be covered.
