### ISSUE TITLE
Book of Calling Machine Operator Incorrect Name

### ISSUE THREAD

**Issue by Neckropemancer** [klikli-dev/occultism#517]
**Describe the bug**
Calling book displays incorrect name to correlated spirit. Shift + right click as well as even just picking up and placing down the book in inventory sets it to another random name

**To Reproduce**
1. Perform machine operator ritual.
2. Observe the spirit's name not matching the book of calling.
3. It can be seen that shift + right clicking or picking up and placing down the book in the inventory changes the name contained in the book's description to a new random name.

**Expected behavior**
It is expected that the book of calling displays the name of the spirit it spawns.

**Screenshots**
![2021-11-17_01 30 12](https://user-images.githubusercontent.com/94467723/142015890-61854f5e-2290-44aa-b2c5-5ad18008be72.png)

![2021-11-17_01 29 59](https://user-images.githubusercontent.com/94467723/142015966-11234019-d921-4603-8a29-5841c0ed1fa4.png)

**System:**
- Occultism Version: 1.16.5-1.18.0
- OS: Windows 8
- Minecraft Version: 1.16.5
- Modpack Link and Version, or list of mods: https://www.curseforge.com/minecraft/modpacks/create-above-and-beyond | version 1.1

**Comment by klikli-dev** [comment]
I could not reproduce: 
- the random name upon summoning (book and spirit matched)
  - this however happens, when using the debug summoning via the ritual dummy item (because then there is no source book item to copy the name from)
- the random name when clicking with the book on the spirit.
  - first time linking the spirit with a cheated-in book correctly updates the name
  - clicking a spirit with a non-matching book obtained via debug summoning just keeps the non-matching name
  
The book however now correctly updates the name when storing a spirit in it.
