### ISSUE TITLE
Unstable otherworld saplings break Botania corporea chat requests

### ISSUE THREAD

**Issue by MojiRS** [klikli-dev/occultism#53]
**Describe the bug**
According to a Botania dev, the issue arises because Occultism uses client-only Minecraft references in 'getTranslationKey' for unstable otherworld saplings (occultism:otherworld_sapling_natural specifically; occultism:otherworld_sapling does not have this issue). My understanding is that the way in which the sapling is registered is not understood or supported by the corporea chat request system, which is presumably related to the sapling appearing in different states depending on the status of the player.

Log file: https://pastebin.com/Zvn9dNbh

**To Reproduce**
1. Set up a corporea network with an index and some storage.
2. Place an unstable otherworld sapling in the storage.
3. Request anything from the index through chat. The request fails, and nothing is shown in chat.

**Expected behavior**
The sapling should be properly searchable in a corporea network as "Unstable Otherworld Sapling".

**System:**
- Occultism Version: 0.2.11
- OS: Windows
- Minecraft Version: 1.15.2
- List of mods: Occultism, Botania (originally found in Enigmatica 5)

**Comment by klikli-dev** [comment]
Sorry for the very late reply on this - real life got in the way a bit and time is still very short on supply.
That issue is definitely on me, the blocks/items that are dependent on player status are admittedly a bit hacky.
I'm not sure the issue can be easily solved, but when I finally get around to the 1.16 update I will try and clean this up. If it works I can backport that fix to 1.15
