### ISSUE TITLE
[1.16.5-1.18.1]Cant always release familiars out of the familiar ring.

### ISSUE THREAD

**Issue by theboo** [klikli-dev/occultism#594]
Reported on discord in version 1.16.5 world of dragons 2 modpack, and I reproduced in occultism 1.18 v1.23.4, can not seem to release familiars from the familiar ring. In 1.18 i can put it in the curio slot then back to hotbar and it will let me place, does not seem to be the case in 1.16.5

https://gyazo.com/2d53776ebb2d986deca55686c4b1c164

**Comment by Dodisosa** [comment]
Just downloaded the mod right now for 1.16.5 and having the same problem. 
Just trying mods out in creative, spawned a familiar with an egg, used the ring, the familiar disappeared and then nothing. Is the ring suppose to update btw, so you know which familiar is in it? Or am I missing something and that's why the familiar doesn't spawn back when I use the ring?
