### ISSUE TITLE
My Game crashes every time I try to look at the pentacles in the Dictionary of Spirits.

### ISSUE THREAD

**Issue by AstaBlackheart** [klikli-dev/occultism#746]
**Describe the bug**
When ever i go to look at different pentacles to turn around and make them. I would click on the desired pentacle and it would crash my game. I am on a server and it crashes and it works perfectly fine on Singleplayer.

**To Reproduce**
1. Open the Dictionary of Spirts
2. Click Pentacles Tab
3. Choose Pentacle to Make
4. Game Crashes

**Expected behavior**
The book to progress further and show me the layout for the pentacle

**System (please complete the following information):**
- Occultism Version: occultism-1.16.5-1.28.0
- OS: Windows 10
- Minecraft Version: 1.16.5
- Modpack Link and Version, or list of mods: 
https://api.technicpack.net/modpack/kinetic-ancient-kingdoms-2

**Additional context**
Crash Logs:
[crash-2022-07-11_06.59.18-client.txt](https://github.com/klikli-dev/occultism/files/9090014/crash-2022-07-11_06.59.18-client.txt)
[crash-2022-07-11_16.31.53-client.txt](https://github.com/klikli-dev/occultism/files/9090015/crash-2022-07-11_16.31.53-client.txt)
[crash-2022-07-11_16.58.23-client.txt](https://github.com/klikli-dev/occultism/files/9090016/crash-2022-07-11_16.58.23-client.txt)
[crash-2022-07-11_22.51.22-client.txt](https://github.com/klikli-dev/occultism/files/9090017/crash-2022-07-11_22.51.22-client.txt)

**Comment by klikli-dev** [comment]
This seems to be an issue with incompatible mod versions (patchouli and occultism, possibly a third party mod interacting as well). 
As occultism 1.16 is no longer supported there will not be a patch for this (plus, the way it looks it would have to be fixed on patchouli's side *I think*).

I would recommend to try a setup with only occultism and its dependencies on their latest 1.16.5 versions and see if that works, and if that is the case either make sure that your modpack has the same versions of the mods, or if that still does not work, remove mods until the culprit is found
