### ISSUE TITLE
Cannot make Shub Niggurath familiar

### ISSUE THREAD

**Issue by Thiccus** [klikli-dev/occultism#785]
**Describe the bug**
I am on 1.19.2 server, its a private server so no heavy restrictions or anything like that, I just cannot get to actually making Shub Niggurath

**To Reproduce**
1. Do the normal chimera thing for goat familiar
2. Take goat to forest
3. Give it eye of ender and black dye
4. Once you give it flint, specifically flint it does not change the goats appearance and the whole thing fails, keeping the goat with half-transformed appearance.

**Expected behavior**
Goat becomes Shub Niggurath

**Screenshots**
n/a

**System (please complete the following information):**
- Occultism Version: occultism-1.19.2-1.44.2
- OS: Windows 10
- Minecraft Version: 1.19
- Modpack Link and Version, or list of mods: https://cdn.discordapp.com/attachments/1017273766943928370/1017273768592281650/Waifuwehr_Modpack.zip

**Additional context**
no additional context

**Comment by klikli-dev** [comment]
This currently does not reproduce in a minimum setup: Occultism + optional and required dependencies. 
It might be that another mod is intercepting the flint right-click on the goat by design or by accident. 
What happens if you give it a flint first? Does the goat get horns?

If this reproduces for you in latest occultism in a clean setup please ping me or reopen this
