### ISSUE TITLE
Translation Error

### ISSUE THREAD

**Issue by Victor-Noli** [klikli-dev/occultism#817]
**Describe the bug**
The achievements/advancements are not translated 

**To Reproduce**
Craft the Dimensional Matrix (for example)

**Expected behavior**
Have a really cool achievement? (See screenshot)

**Screenshots**

![image](https://user-images.githubusercontent.com/57479840/200035168-eb311c6b-e8ee-4d61-a699-5b0d41d6553b.png)

**System (please complete the following information):**
- Occultism Version: 1.16.5-1.29.1
- OS: [e.g. Windows] : Windows 10
- Minecraft Version: 1.16.5
- Modpack Link and Version, or list of mods: 
Modlist : 
![image](https://user-images.githubusercontent.com/57479840/200036124-63d696dc-e445-46cb-9cce-2f947ed69f1c.png)
![image](https://user-images.githubusercontent.com/57479840/200036215-acfb3053-a4ec-4f69-85b0-6e785dbd56fd.png)
Forge Version used : 36.2.39

**Comment by klikli-dev** [comment]
@Victor-Noli thanks for the report!
After some investigations it turns out this is not actually a bug after all, these are "hidden" advancements that have no translation because they are intended only for quests.

I am not sure why they are shown in chat, the json config still contains: ` "announce_to_chat": false,` and `    "show_toast": false,`

It might be that minecraft is ignoring these instructions, at least when adding the advancement via command, I am not sure if it also happens when getting it via ritual.

Either way, it is not planned to add translations for these currently so I am closing this for now
