### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by TobiDoes** [klikli-dev/occultism#820]
**Describe your problem**
Any Time I load up a SERVER not the game 
Crash Report: https://pastebin.com/1mCicg0h

**System (please complete the following information):**
- Minecraft Version 1.19.2
- Modpack Link and Version, or list of mods (https://www.curseforge.com/minecraft/modpacks/mystic-horizons) (I am working on an Update)
- Specific mods that you experience compatiblity issues with

**Comment by klikli-dev** [comment]
I think you have an underlying problem here, you are getting identical errors from Quark, Occultism, SophisticatedBackpacks and ImmersiveEngineering.

The log does not seem to indicate occultism causing this (at least I do not see any known problems here).
My recommendation would be to join the forge discord https://discord.gg/forge and ask in #tech-support if they know this issue

I will close this issue for now - if the forge team does indicate that occultism is at fault or needs to change anything, please comment here and ping me so I can reopen it
