### ISSUE TITLE
Weird bug with occultism textures

### ISSUE THREAD

**Issue by ZirkXl** [klikli-dev/occultism#859]
**Describe the bug**
Whenever i use anything of the occultism mod the texture just changes

**To Reproduce**
1. Throw Demon dreams fruit on top of netherite
2. Light the fire
4. And it just changes

**Expected behavior**
Just convert to purple fire

**Screenshots**
![image](https://user-images.githubusercontent.com/37722358/205672877-423f64ac-ccc6-4dac-9744-fccce8611dce.png)
This is actually the purple fire with another texture (i can even step on it like if it was a solid block)

**System (please complete the following information):**
- Occultism Version: occultism-1.19.2-1.55.4.jar
- OS: [e.g. Windows] Win10 Home
- Minecraft Version: 1.19.2
- Modpack Link and Version, or list of mods: 
![image](https://user-images.githubusercontent.com/37722358/205673254-4996fddd-506f-42b9-a01b-e6a96b006223.png)

**Additional context**

**Comment by klikli-dev** [comment]
@ZirkXl thank you for the report!
Does this issue reproduce with just occultism + dependencies?

As occultism (like most mods) uses vanilla mechanics for all blocks, including fire, it is unlikely to be caused by occultism directly. In most cases issues like that are caused by interactions with another mod, that changes vanilla rendering behaviour (for example, to attempt to improve performance). 

If it happens with occultism alone I can investigate what is going on, otherwise the next step would be to find the mod that causes it, and report at their Issue tracker too to find a solution together

**Comment by klikli-dev** [comment]
Closed as stale, please ping me to reopen if it still persists
