### ISSUE TITLE
Upgrading 1.60.0 to 1.65.1 triggers a "smartbrainlib" dependency missing message, adding the dependency causes a startup crash

### ISSUE THREAD

**Issue by sciguyryan** [klikli-dev/occultism#874]
**Describe the bug**
Upgrading 1.60.0 to 1.65.1 triggers a "smartbrainlib" required message, adding the dependency causes a startup crash. As such I've been unable to upgrade to the specific version.

**To Reproduce**
1. Upgrade from version 1.60.0 to 1.65.1.
2. Attempt to boot the pack.
3. Receive a Forge missing dependency notification.

**Expected behavior**
Either require the smartbrainlib dependency be added, or boot without it.

**Screenshots**
Not applicable here.

**System (please complete the following information):**
- Occultism Version: 1.60.0
- OS: Windows 11.
- Minecraft Version: 1.19.2
- Modpack Link and Version, or list of mods: Custom pack.

**Additional context**

**Comment by klikli-dev** [comment]
Please delete forgebrainlib from your modpack.
Sadly it is not possible on curse to specify that a dependency should be removed/exchanged

**Comment by sciguyryan** [comment]
I don't actually have it in the pack, but upgrading to 1.65.1 without adding the dependency will not allow booting as Forge detects that there is a missing dependency.

As of now I'm on version 1.60.0 and can't upgrade to 1.65.1.

**Comment by klikli-dev** [comment]
If you are >= 1.59 then you have *Forge*brainlib as a dependency. 
But >= 1.63 needs *Smart*brainlib, the upstream open source version.

Due to some technical issues it seems some versions of Forgebrainlib cannot coexist with Smartbrainlib. 
Thus when you update to >= 1.63 you need to manually remove *forge*brainlib from your modpack config in the launcher or mod folder (depending on how you are setting up your mod pack), but keep the *smart*brainlib  that the launcher should install for you
