### ISSUE TITLE
Machine Operators attempting to input items in wrong location

### ISSUE THREAD

**Issue by bigfoott** [klikli-dev/occultism#878]
**Describe the bug**
Machine Operator is attempting to place items in the wrong input (see video below)

**To Reproduce**
See video: https://www.youtube.com/watch?v=U5Ba5iwpHlk

**Expected behavior**
The machine operator should try to input on the selected barrel.

**Screenshots**
https://www.youtube.com/watch?v=U5Ba5iwpHlk

**System (please complete the following information):**
- Occultism Version: 1.19.2-1.60.0
- OS: Windows
- Minecraft Version: 1.19.2
- Modpack Link and Version, or list of mods: ATM8 - https://www.curseforge.com/minecraft/modpacks/all-the-mods-8

**Additional context**
Side note, I'm also running into [a different issue](https://github.com/klikli-dev/occultism/issues/879) at the same time, not sure if they're related.

**Comment by klikli-dev** [comment]
This seems to be a pathfinding issue actually.
He is attempting to place in the right barrel, but minecraft navigates a weird path access the side that was given for insert (up) because it is blocked by the machine above it.

In 3fbaba0c70e3e6c7c92aa6a824d305d0f1581019 I will disable line of sight checks so he might be able to access the machine anyway, but meanwhile you can try to set an insert facing that corresponds to the front side of the barrel (based on your minimap, north I think)

**Comment by bigfoott** [comment]
Hi! So while it's not in the video, I do believe I tried changing the input side to north while doing some random testing, and it still tried to go up to the side like in the video for some reason. At this point though I've got it working as intended directly into the machines rather than into a bartel, so it's all good, thanks!
