### ISSUE TITLE
[Bug] In the ATM8 modpack thunderstorm ritual only causing snow

### ISSUE THREAD

**Issue by gotget1337** [klikli-dev/occultism#899]
currently in a snow biome and I have summoned 3 different Afrit thunderstorm spirits using the Abaras' Conjure Thunderstorm ritual and each time he spawned It began to snow but no lightning was spawned at all. The afrit himself just punches the air from the moment he spawns to his death and has smoke particles at his feet, the smoke makes me think I need to throw him something but the Dictionary of Spirits doesn't say anything of the sort.

**Comment by klikli-dev** [comment]
Hmm I am not sure if that can be fixed. If the weather changes then the code is running as intended ( you do not need to give him additional items ).  What happens if you run the command to summon a thunderstorm?

I am using the same code, so unless vanilla changed it on their end both should produce the same result

**Comment by klikli-dev** [comment]
Closed as stale
