### ISSUE TITLE
[BUG]: The game crashed whilst rendering overlay --  Exit Code 1

### ISSUE THREAD

**Issue by LadyHaley** [klikli-dev/occultism#910]
### Bug Description

Game crash when launching game

### Logs and Crash Reports

https://hastebin.com/share/uwosagufok.perl

### Screenshots and/or Videos

My Mod List
![image](https://user-images.githubusercontent.com/3754909/229341475-8a6da92b-6eba-4dfa-872d-41901236f2e5.png)

### Bug Reproduction

Launch game no success

### Expected Behavior

Launch game success

### Minecraft Version

1.18.2

### Mod Version

oculus-1.5.2

### Modpack

Other

**Comment by klikli-dev** [comment]
@LadyHaley It looks like this is caused by oculus:

`java.lang.IllegalAccessError: failed to access class com.mojang.blaze3d.platform.GlStateManager$TextureState from class net.coderbot.iris.gl.IrisRenderSystem$DSAARB (com.mojang.blaze3d.platform.GlStateManager$TextureState is in module minecraft@1.18.2 of loader 'TRANSFORMER' @6c1cfa53; net.coderbot.iris.gl.IrisRenderSystem$DSAARB is in module oculus@1.5.2 of loader 'TRANSFORMER' @6c1cfa53)`

This, however, is the repository for Occultism, an unrelated mod :)
