### ISSUE TITLE
Create above and beyond modpack, Machine Operator Crash loop

### ISSUE THREAD

**Issue by Mogwr** [klikli-dev/occultism#962]
I was setting up the machine operator spirit to link to my storage actuator and was going to see how it moves stuff and went to put an item in its inventory with Shift Click, this instantly crashed my game and now the world crashes whenever i load it.

**To Reproduce**
1. tier 1 dimensional storage settup, nearly full
2. summon machine operator
3. place item in machine operators hand while linked to the storage actuator

**Expected behavior**
It would move the item to the storage inventory

**System (please complete the following information):**
occultism-1.16.5-1.20.1.jar
windows 11
- Minecraft Version: 1.16.5
- Modpack Link and Version, or list of mods: 
- https://www.curseforge.com/minecraft/modpacks/create-above-and-beyond latest release

**Additional context**

[crash-2023-08-09_16.22.38-server.txt](https://github.com/klikli-dev/occultism/files/12306737/crash-2023-08-09_16.22.38-server.txt)

thanks in advanced for any help! Love this mod a lot, top 3 for me!

**Comment by klikli-dev** [comment]
@Mogwr Sadly I cannot fix this as 1.16.5 is no longer supported, and C: A&B makes a lot of changes and adds a lot of mods with mixins that may interfere with occultism.
I can only say that this bug is not a known one, so its possible that there is a way around it.

Looking at the changelog of the latest A&B version (1.3) it has occultism 1.16.6-1.23.1 which is higher than yours, so you could try that one (https://www.curseforge.com/minecraft/modpacks/create-above-and-beyond/files/3567550)
