### ISSUE TITLE
Wild hunt self-kill by fire does not work

### ISSUE THREAD

**Issue by uhloin** [klikli-dev/occultism#972]
Version occultism-1.20.1-1.87.1.jar 

Wild Hunt ritual works with some methods of suicide, but not self-burning.
If use Splint and Steel on the floor (empty place without glyph) and stand in the fire and wait for death, the ritual does not started.

**Comment by klikli-dev** [comment]
That is not considered a bug, or at least not one occultism can fix - burning does not report the player as killer, however for both reasons of performance (to not handle all deaths) and for gameplay reasons only player kills count towards rituals

**Comment by klikli-dev** [comment]
Note: A villager should work as sacrifice for scenarios where you cannot sacrifice a friend

**Comment by uhloin** [comment]
Player deaths is rare enough event to affect to performance: on any death just check it was player, do not check cause of death.
But it's your choice of course.
Just as tip: trick pf death with totem undying also doesn't work, but should work as award for cunning ;)

**Comment by klikli-dev** [comment]
That is generally a good idea, however rituals can accept any entity as sacrifice (governed by recipe), it just happens that this one ritual has players as default sacrifice. 
So rituals listen to all entity death's by default, but handle only those caused by players.

As for totem of undying: I think that does not cause the firing of a death event or rather, cancels the death event before other mods can capture it. Do you know of any mod that detects deaths despite the totem preventing it? Then maybe that could be supported as its a neat idea

**Comment by uhloin** [comment]
I'm not familiar with mod programming, but I would use any death instead of only caused by players. My logic is... if player made a pentacle, then there is almost 100% chance any death in it is caused by player directly or indirectly (trap etc). So it's sacrifice too. Except deaths from summoned demons, but they probably won't work because sacrifice bowls are already empty.

About totem I know only mod which checks totem in inventory on death (Elemental Craft), but it's not what you asked. May be you like this idea :
https://mcreator.net/forum/95709/detect-when-player-uses-totem
