### ISSUE TITLE
Divination rod not divining

### ISSUE THREAD

**Issue by Sovion** [klikli-dev/occultism#999]
Having created the divination rod and attuned it to iesnium ore, I right-clicked it in the nether and.. nothing. No highlights, no nothing. Flew around for a bit, nothing. Spawned in an iesnium ore block, right-clicked to see if it would highlight - didn't. Changed the config alternative rendering method to true - still nothing. No clue what to do with that.

**Expected behavior**
The divining rod to work as it's intended to: upon right clicking an attuned rod it should highlight the block it's attuned to in a given area. (I do have the goggles equipped)

**Screenshots**
I don't think screenshots are necessary.

**System (please complete the following information):**
- Occultism Version: 1.88.1
- OS: [e.g. Windows] Windows 10
- I'm running an  NVIDIA GeForce RTX 3060 (MSI) graphics card (if that helps)
- Minecraft Version: 1.20.1
- Forge Version: 47.2.1
- Modpack Link and Version, or list of mods: 

1.20.1-forge-Epic-Knights-8.7
aether-1.20.1-1.0.0-beta.1.3-neoforge
architectury-9.1.12-forge
ars_nouveau-1.20.1-4.7.2-all
ars_ocultas-1.20.1-1.1.0-all
bellsandwhistles-0.4-1.20.X
bloodmagic-1.20.1-3.3.2-44
bygonenether-1.3.2-1.20.x
cloth-config-11.1.106-forge
collective-1.20.1-6.72
CrabbersDelight-1.20.1-1.1.3
create-1.20.1-0.5.1.d
createaddition-1.20.1-1.1.0
createdieselgenerators-1.20.1-1.1d
createoreexcavation-1.20-1.4.0
create-stuff-additions1.20.1_v2.0.4a
Dynamic-Music-Mod-Forge-1.20.1
embeddium-0.2.1+mc1.20.1
EnchantingInfuser-v8.0.2-1.20.1-Forge
extendedgears-2.1.0-1.20.1-0.5.1.c-forge
FarmersDelight-1.20.1-1.2.3
forbidden_arcanus-1.20.1-2.2.2
geckolib-forge-1.20.1-4.2.3
growthcraft-1.20.1-9.1.0
growthcraft-1.20.1-9.1.1
immersive_melodies-0.1.0+1.20.1-forge
jei-1.20.1-forge-15.2.0.27
map_atlases-1.20-5.9.3-all
map_atlases-1.20-5.10.10-all
modonomicon-1.20.1-forge-1.40.0
moonlight-1.20-2.8.60-forge
mutil-1.20.1-6.1.1
nethersdelight-1.20.1-4.0
occultism-1.20.1-1.88.1
oculus-mc1.20.1-1.6.9
Patchouli-1.20.1-81-FORGE
physics-mod-pro-v162b-forge-1.20.1
PuzzlesLib-v8.0.24-1.20.1-Forge
smallships-forge-1.20.1-2.0.0-a2.3.3
SmartBrainLib-forge-1.20.1-1.12
soundphysics-forge-1.20.1-1.1.2
Steam_Rails-1.5.1+forge-mc1.20.1
supplementaries-1.20-2.6.26
Terralith_1.20.1_v2.4.5
tetra-1.20.1-6.0.0
theurgy-1.20.1-1.7.0
tomeofblood-1.20.1-0.2.1-all
treeharvester-1.20.1-8.2
valhelsia_core-forge-1.20.1-1.1.1
valhelsia_furniture-forge-1.20.1-1.1.2
valhelsia_structures-forge-1.20.1-1.1.0

**Comment by klikli-dev** [comment]
If theurgy is present, the divination rod does not create a block highlight, instead it "shoots" a particle effect towards the target block. 

Please click and hold the rod until the item use is finished (like you would a bow). Then briefly right-click the rod repeatedly while turning in a circle - do you see a particle effect? 
Further, if you stand next to your spawned iesnium, is the crystal of the rod white or purple? 

Finally, when spawning in iesnium please be aware that the block named "iesnium" in jei is the dropped block, but not the block in the world. Instead search for "netherrack" and use the one that shows as being added by occultism. If placed down and you do not use goggles or third eye the ore should show as netherrack, otherwise the rod will not find it.

**Comment by Sovion** [comment]
Helped, thank you.
